name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "11", "21"]
        clojure: ["1.8", "1.9", "1.10"]
        
    name: Java ${{ matrix.java }} Clojure ${{ matrix.clojure }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.lein
        key: ${{ runner.os }}-lein-java${{ matrix.java }}-clojure${{ matrix.clojure }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-java${{ matrix.java }}-

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Install Leiningen
      run: |
        curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x lein
        sudo mv lein /usr/local/bin/

    - name: Verify Leiningen installation
      run: lein version

    - name: Install dependencies
      run: lein with-profile dev,${{matrix.clojure}} deps

    - name: Run tests
      run: lein with-profile dev,${{matrix.clojure}} test :all

    - name: Check Reflection Warnings
      run:  '! lein with-profile dev,${{matrix.clojure}} check 2>&1 | egrep "Reflection warning|Performance warning"'
